### ISSUE TITLE
dfu-programmer error on user page

### ISSUE THREAD

**Issue by cludfulogin** [dfu-programmer/dfu-programmer#13]
I am using dfu-programmer to test programming an atmel MCU. it progrmmed the main applicaiton .hex file to the flash memory is fine. But when I have a smaller .hex file to program to the user page, the software shown error on complaining the size of the .hex file. Looks like it expect to at lease have the fine size great or equal to the page size which is 512 bytes. so I create a .hex file with 512 bytes but still show hte same error as (when turn debug option on ):

atmel.c:1629: Expected message length of 592, got -5.

I checked the source code and knew the location where thrown the error but don't know why. 

If someone programmed the user page before and can help me out.

The command I used to program user page is where have problem.
dfu-programmer at32uc3c0512 flash --user --debug=51 applicationheader.hex --force

but the same command to program flash pages are Ok.
dfu-programmer at32uc3c0512 flash --debug=51 application.hex --suppress-bootloader-mem -- force

Thanks,
Chester

**Comment by swinman** [comment]
can you share the applicationheader.hex file that you are using?  Does it give the correct address for the user page?  Also, is there a configuration word at the end of the user page for your chip?  You can test that using `dfu-programmer at32uc3c0512 read --user`

**Comment by M4iKK** [comment]
For me this works fine. I think this case can be closed if @cludfulogin has no objection.
