### ISSUE TITLE
Missing the 0.7.0 tag and possibly the 0.7.1 tag

### ISSUE THREAD

**Issue by jszakmeister** [dfu-programmer/dfu-programmer#17]
I just noticed that the 0.7.0 release tag is missing from the GitHub repo, and if 0.7.1 was recently released, then it's missing too. :-)

**Comment by skirridsystems** [comment]
Thanks for noticing.
I have created both tags and added the release notes for 0.7.1

**Comment by jszakmeister** [comment]
Great!  Thanks!
