### ISSUE TITLE
AT90USBKEY2: dfu-programmer doesn't work

### ISSUE THREAD

**Issue by pozzugno** [dfu-programmer/dfu-programmer#32]
I'm trying to use dfu-programmer with AT90USBKEY2 evboard from Atmel. It doesn't work. Flip software from Atmel works well.

I'm using an hex file as an application example. Erase operation is ok. Flash operation isn't ok:

```
dfu-programmer at90usb1287 flash diana5prog.hex
0%                            100%  Programming 0x8D80 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x1E000 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
Validating...  ERROR
31580 invalid bytes in program region, 0 outside region.
FAIL
Memory did not validate. Did you erase?
```

I read the Flash memory after dfu-programming (with a JTAG programmer) and the content is really different than the original hex file. There identical sections, but there are different sections.
It seems some section are written at a different address (maybe at a different Flash page?).

![image](https://cloud.githubusercontent.com/assets/15036968/18246963/a8bda736-736f-11e6-9de4-1295d7b21df1.png)

Again, Flip software works well.

**Comment by skirridsystems** [comment]
Closing, as no further input after 6 years
