### ISSUE TITLE
dfu-programmer doesn't work on 32-bit Windows

### ISSUE THREAD

**Issue by NoahAndrews** [dfu-programmer/dfu-programmer#35]
![image](https://cloud.githubusercontent.com/assets/10224994/20785529/8f14079c-b76e-11e6-8ecb-3b366b96fe42.png)

On 32-bit Windows, the filename it should be looking for is  libusb0_x86.dll.

**Comment by NoahAndrews** [comment]
For anyone finding this in the future, you need to install the Atmel driver before dfu-programmer will even launch.

**Comment by skirridsystems** [comment]
Hi Noah,
Did you run the windows installer? That includes the USB driver and it
should install when you plug the USB device in.
Simon
