### ISSUE TITLE
cat: dfu_completion :No such file or directory

### ISSUE THREAD

**Issue by vagha** [dfu-programmer/dfu-programmer#43]
After running ./bootstrap.sh this is what terminal is displaying

**Comment by swinman** [comment]
what is being displayed?  what system are you using?

**Comment by vagha** [comment]
cat: dfu_completion :No such file or directory
i am using mac

**Comment by ignatenkobrain** [comment]
should be fixed by #45

**Comment by vagha** [comment]
still the same response

**Comment by rudenick1** [comment]
I had to create directory dfu proggrammer.d in the path specified by the bootstrap with mkdir command

**Comment by cinderblock** [comment]
If this is not fixed, please re-open.
