### ISSUE TITLE
is this abandonware?

### ISSUE THREAD

**Issue by GianniGi** [dfu-programmer/dfu-programmer#51]
I find this program very helpful, and I wonder why it's not updated anymore.  I hope that someone may pick it up! Thanks to the developers for the great work done until now.

**Comment by swinman** [comment]
I'm not the maintainer but I've made some updates over time.  I don't have
much extra time to spend on updates that dont directly impact my ability to
use the tool.

**Comment by szszszsz** [comment]
@GianniGi 
I would say because it is complete and there is no need ;-)
Check out [other forks](https://github.com/dfu-programmer/dfu-programmer/network) and people working on them - perhaps they would be eager to develop it further and add features you desire.
@swinman thank you for your work!

**Comment by GianniGi** [comment]
@swinman thank you! great tool. Too bad that ubuntu 17.10 was delivered with an old version (two years old). Maybe because it was marked as stable and the new one is the instable one?

**Comment by swinman** [comment]
actually, dfu-programmer installed on ubuntu is 0.6.1, which has some
functionality missing and is broken for putting stuff on the user page.
the newer (yet now quite old) dfu-programmer 0.7.2 should be much improved
and has tab completion (we routinely use it on ubuntu).  would be great if
they could update to this version..

**Comment by anthraxx** [comment]
There is no 0.7.2 tag available on git, can we at least get a tag pushed? :smiley_cat:

**Comment by wanglouxiaozi** [comment]
@swinmanIs It convenient for you to add support for STM32F10X series MCU? STM32F10X use the dfu program project(en. Stsw-stm32121 \ stm32_usb-fs-device_lib_v4.1.0 \Projects\Device_Firmware_Upgrade), looking forward to your reply.

**Comment by wanglouxiaozi** [comment]
@swinman  Is it convenient for you to add support for STM32F10X series MCU? STM32F10X use the dfu program project(en. Stsw-stm32121 \ stm32_usb-fs-device_lib_v4.1.0 \Projects\Device_Firmware_Upgrade), looking forward to your reply.

**Comment by swinman** [comment]
Hi - I don't see any reason why this couldn't be done, but I personally
don't have plans to implement support for this chip.  If you add it, we'll
review and would consider merging but we won't be able to test that it
works without a starter kit.

-Walker

**Comment by anthraxx** [comment]
@skirridsystems gentle reminder for tagging 0.7.2

**Comment by cinderblock** [comment]
@anthraxx That has been fixed
