### ISSUE TITLE
Release asset `dfu-programmer-1.0.0.tar.gz` is missing file `update-bash-completion.sh`

### ISSUE THREAD

**Issue by bluecube** [dfu-programmer/dfu-programmer#88]
Release asset  `dfu-programmer-1.0.0.tar.gz` is missing file `update-bash-completion.sh`

`./configure && make` fails with `make: *** No rule to make target 'update-bash-completion.sh', needed by 'dfu_programmer'.  Stop.`.

0.9.0 works fine.

**Comment by cinderblock** [comment]
Thank you for this report. I will look into it.

**Comment by cinderblock** [comment]
I think this was fixed with 997c851df93d92155793ca4ff5e073bd42455534 and v1.1.0
